services:
  php:
    build: 
      context: .
      dockerfile: docker/php/Dockerfile
    expose:
      - 8080
    volumes:
      - ./app:/var/www/html/app
      - ./index.php:/var/www/html/index.php
    ports:
      - 8080:80
    networks:
      - app-network


  databank:
    build: 
      context: .
      dockerfile: docker/mysql/Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridgef